version: '3.9'

services:
  django:
    container_name: django
    build: .  
    volumes:
      - ./SocialMediaApp   
    command: python manage.py runserver 0.0.0.0:8000 
    ports:
      - 8000:8000

    environment:
      - DEBUG=1
      - SECRET_KEY=abc123
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
